services:
  db:
    image: ${MYSQL_IMAGE}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - /home/song/volume/ssafy_home:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: zipchack_MySQL

  config-server:
    image: ${CONFIG_SERVER_IMAGE}
    ports:
      - '${CONFIG_SERVER_PORT}:9000'
    volumes:
      - /home/song/ssafy_home/config_server_env.yaml:/env.yaml
    healthcheck:
      test: ["CMD", "curl", "-i", "http://localhost:9000/actuator/health | grep -q '\"status\":\"UP\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    environment:
      - SPRING_CONFIG_IMPORT=optional:file:/env.yaml
    container_name: zipchack_config_server

  news-crawling:
    image: ${NEWS_CRAWLING_IMAGE}
    ports:
      - '${NEWS_CRAWLING_PORT}:8000'
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - APPLICATION_NAME=${NEWS_APPLICATION_NAME}
      - PROFILE=${NEWS_PROFILE}
      - CONFIG_SERVER_USERNAME=${CONFIG_SERVER_USERNAME}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD}
    container_name: zipchack_news_crawling

  scheduler:
    image: ${SCHEDULER_IMAGE}
    restart: always
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://${CONFIG_SERVER_URL}
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USERNAME}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PASSWORD}
    container_name: zipchack_scheduler